### ISSUE TITLE
chosen-rails/rspec `require': cannot load such file

### ISSUE THREAD

**Issue by jcward10** [tsechingho/chosen-rails#80]
I tried putting `require 'chosen-rails/rspec'` in bot the spec_helper and rails_helper. Both gave me the same error 
```
spec/spec_helper.rb:5:in `require': cannot load such file -- chosen-rails/rspec (LoadError)
```

Please help

**Comment by rpbaptist** [comment]
I ran into the same problem and that's because this feature is not yet integrated in the latest tag.

I simply copied the contents of [the refered file](https://github.com/tsechingho/chosen-rails/blob/master/lib/chosen-rails/rspec.rb) and added the code to `spec/support/chosen.rb` which I was loading into my test environment already by having this in my `rails_helper.rb` file:
`Dir[Rails.root.join("spec/support/**/*.rb")].each { |file| require file }`

**Comment by jcward10** [comment]
Thanks for pointing that out!

**Comment by BM5k** [comment]
FYI: It's _still_ not included in the latest tag.

**Comment by jcward10** [comment]
Thanks BM5k ... I pretty much rewrote it myself as an rspec helper

**Comment by tsechingho** [comment]
I release 1.5.1, lib/rspec.rb is included now.
